name: Build RAM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Add NuGet source
        run: nuget sources Add -Name "nuget.org" -Source https://api.nuget.org/v3/index.json

      - name: Restore NuGet packages
        run: nuget restore RBXAltManager.sln -Verbosity detailed

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        run: msbuild RBXAltManager.sln /p:Configuration=Release /verbosity:minimal

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RAM
          path: '**/bin/Release/'
