name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up NuGet
      uses: nuget/setup-nuget@v1

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Ensure Packages Folder Exists
      run: |
        if (-Not (Test-Path "$Env:GITHUB_WORKSPACE\packages")) { mkdir "$Env:GITHUB_WORKSPACE\packages" }
      shell: pwsh

    - name: Build the Solution
      run: MSBuild.exe "$Env:GITHUB_WORKSPACE\RBXAltManager.sln" -p:Configuration=Release
      timeout-minutes: 5

    - name: Create Archive
      run: |
        cd "$Env:GITHUB_WORKSPACE"
        tar -a -cvf RobloxAccountManager.zip -C "RBX Alt Manager/bin/Release" .
      shell: pwsh

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Build
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./RobloxAccountManager.zip
        asset_name: RobloxAccountManager.zip
        asset_content_type: application/zip
