name: Build RAM

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        run: msbuild RBXAltManager.sln /p:Configuration=Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RAM
          path: '**/bin/Release/'
