name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore RBXAltManager.sln

    - name: Build with MSBuild
      run: msbuild RBXAltManager.sln /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: RBXAltManager
        path: "**/bin/Release/"
