name: Build .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish EXE
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish
      # Adjust -r win-x64 for your target runtime (win-x64, win-x86, etc.)

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: roblox-account-manager-exe
        path: ./publish/*
