name: Build and Release

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore "$Env:GITHUB_WORKSPACE\RBXAltManager.sln"
      shell: pwsh

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build Solution
      run: msbuild "$Env:GITHUB_WORKSPACE\RBXAltManager.sln" /p:Configuration=Release /p:Platform="Any CPU"
      shell: cmd

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildOutput
        path: |
          ${{ github.workspace }}\RBX Alt Manager\bin\Release\

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release Build
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}\RBX Alt Manager\bin\Release\RBX Alt Manager.exe
        asset_name: RBX-Alt-Manager.exe
        asset_content_type: application/octet-stream
